version: '3.8'

networks:
  network_bridge:
    ipam:
      config:
        - subnet: 172.24.0.0/16

services:

  # DB
  mysql:
    image: mysql
    restart: always
    container_name: chatRedis-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chatRedis
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      TZ: Asia/Seoul
    volumes:
      - ./docker/MySQL/my.cnf:/etc/mysql/my.cnf  # 마운트할 my.cnf 파일
    networks:
        network_bridge:
            ipv4_address: 172.24.0.3

  #  redis
  redis:
    image: redis
    restart: always
    container_name: chatRedis-redis
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    networks:
      network_bridge:
        ipv4_address: 172.24.0.2

  # spring-boot app
  backend:
    restart: always
    container_name: chatRedis-backend
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://chatRedis-mysql:3306/chatRedis
      - SPRING_REDIS_HOST=chatRedis-redis
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_PASSWORD=redis-pw
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    networks:
      network_bridge:
        ipv4_address: 172.24.0.4
